spring:
  application:
    name: security-jwt
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_jwt?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true

server:
  port: 8081

security:
  jwt:
    secret-key: NkB0NmZVBmXqW5fFhaMztzEq+u5vPX7E/ogVl6mL5mw=
    expiration-time: 3600000